# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: ads-sls-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

provider:
  name: aws
  region: us-west-2
  profile: impakt
  runtime: java8
  stage: ${opt:stage, 'dev'}


# you can add packaging information here
package:
  artifact: target/${self:service}-${self:provider.stage}.jar

functions:
  heroStats:
    handler: com.serverless.HeroStatsHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/hero-stats
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                start: true
                end: true

  roleDurations:
    handler: com.serverless.RoleDurationsHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/role-durations
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                start: true
                end: true

  stepDurations:
    handler: com.serverless.StepDurationsHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/step-durations
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                start: true
                end: true

  ASAPInspector:
    handler: com.serverless.ASAPInspectorHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/asap-inspector
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                start: true
                end: true
                orgCode: true

  Sankey:
    handler: com.serverless.SankeyHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/sankey
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                start: true
                end: true
