# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: ads-sls-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

provider:
  name: aws
  region: us-west-2
  profile: impakt
  runtime: java8
  stage: ${opt:stage, 'dev'}


# you can add packaging information here
package:
  artifact: target/${self:service}-${self:provider.stage}.jar

functions:
  heroStats:
    handler: com.serverless.HeroStatsHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/hero-stats
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                start: true
                end: true

  roleDurations:
    handler: com.serverless.RoleDurationsHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/role-durations
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                start: true
                end: true
                asap: true

  stepDurations:
    handler: com.serverless.StepDurationsHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/step-durations
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                start: true
                end: true
                asap: true

  ASAPInspector:
    handler: com.serverless.ASAPInspectorHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/asap-inspector
          method: post
          cors:
            origin: '*'
          request:
            parameters:
              querystrings:
                start: true
                end: true
                orgCode: true

  SankeyDiagram:
    handler: com.serverless.SankeyDiagramHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/sankey-diagram
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                start: true
                end: true

  DetailRole:
    handler: com.serverless.DetailRoleHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/detail-role
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                start: true
                end: true
                casenumber: true

    DetailStep:
      handler: com.serverless.DetailStepHandler
      timeout: 30
      events:
        - http:
            path: /sample-data-2/detail-step
            method: get
            cors: true
            request:
              parameters:
                querystrings:
                  start: true
                  end: true
                  casenumber: true

  DetailHero:
    handler: com.serverless.DetailHeroHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/detail-hero
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                asap: true

  AsapDetail:
    handler: com.serverless.AsapDetailHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/asap-detail
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                asap: true

  UserTime:
    handler: com.serverless.UserTimeHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/user-time
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                asap: true

  AllOrganizations:
    handler: com.serverless.AllOrgsHandler
    timeout: 30
    events:
      - http:
          path: /sample-data-2/org-codes
          method: get
          cors: true
